resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: NodeTool@0
    displayName: Use Node 21.7.2
    inputs:
      versionSpec: 21.7.2
  - task: Npm@1
    displayName: npm custom
    inputs:
      command: custom
      verbose: false
      customCommand: install --force
  - task: CmdLine@2
    displayName: Command Line Script
    inputs:
      script: >
        echo Compiling Build Starts Now

        set NODE_OPTIONS=--max-old-space-size=4184 && npm run build

        echo Build Compiled and Ready
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: build
...
