trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: windows-latest

steps:
  - checkout: self
    clean: true
    fetchTags: false

  - task: NodeTool@0
    displayName: Use Node.js 22.x
    inputs:
      versionSpec: 22.x

  - script: npm ci
    displayName: Install dependencies

  - script: npm run lint
    displayName: Run lint checks

  - script: npm run build
    displayName: Build application
    env:
      NODE_OPTIONS: --max-old-space-size=4184

  - task: PublishBuildArtifacts@1
    displayName: Publish build artifact
    inputs:
      PathtoPublish: dist
      ArtifactName: drop
